export const auth = {
  login: {
    title: "Bienvenido",
    subtitle: "Inicia sesión para entrar a tu Cuadra.",
    emailLabel: "Correo electrónico",
    passwordLabel: "Contraseña",
    rememberMe: "Mantenerme conectado",
    submit: "Entrar",
    forgot: "¿Olvidaste tu contraseña?",
    errors: {
      invalidCredentials: "Correo o contraseña incorrectos.",
      inactive: "Tu cuenta está desactivada. Contacta al dueño del gym.",
      rateLimit: "Muchos intentos. Espera 1 minuto antes de volver a intentar.",
      offline: "Necesitas internet para iniciar sesión la primera vez.",
      generic: "Algo salió mal. Vuelve a intentar en un momento.",
    },
    trialExpired: {
      title: "Tu prueba terminó",
      body: "Para seguir usando Cuadra, activa tu plan.",
      activate: "Activar Cuadra Pro",
      later: "Recordármelo después",
    },
  },
  forgot: {
    title: "Recuperar contraseña",
    subtitle: "Te enviaremos un correo con un link para crear una contraseña nueva.",
    emailLabel: "Tu correo electrónico",
    submit: "Enviar instrucciones",
    sent: "Si tu correo está registrado, recibirás un email en unos minutos. Revisa también la carpeta de spam.",
    backToLogin: "Volver al inicio de sesión",
  },
  reset: {
    title: "Crea una contraseña nueva",
    subtitle: "Mínimo 8 caracteres. Que sea fácil de recordar para ti.",
    newPasswordLabel: "Nueva contraseña",
    confirmPasswordLabel: "Repite la contraseña",
    submit: "Guardar contraseña",
    success: "Contraseña actualizada. Inicia sesión con tu nueva contraseña.",
    invalidLink: "Este link ya no es válido. Solicita uno nuevo.",
    expired: "Este link expiró (válido por 1 hora). Solicita uno nuevo.",
    requestNew: "Solicitar nuevo link",
    mismatch: "Las contraseñas no coinciden.",
    short: "Mínimo 8 caracteres.",
  },
  signup: {
    welcome: "Bienvenido a Cuadra",
    subtitle: "Vamos a poner tu gym a cuadrar en 5 minutos.",
    fullName: "Tu nombre completo",
    email: "Tu correo electrónico",
    password: "Contraseña",
    confirmPassword: "Repite la contraseña",
    submit: "Crear mi cuenta",
    errors: {
      emailFormat: "Ese correo no se ve bien. Revísalo.",
      emailExists: "Este correo ya tiene una cuenta. ¿Quieres iniciar sesión?",
      passwordShort: "Tu contraseña debe tener al menos 8 caracteres.",
      passwordMismatch: "Las contraseñas no coinciden.",
      offline: "Necesitas internet solo esta vez para crear tu cuenta. Una vez creada, Cuadra funciona sin internet.",
    },
  },
};
