export const auth = {
  // Grilla de operadores con PIN — el flujo primario en recepción tras el
  // refactor de auth. Email + password sigue accesible como link discreto
  // "iniciar sesión con correo" para recuperación (PIN olvidado, primer
  // login antes de tener PIN configurado).
  pinLogin: {
    title: "¿Quién entra?",
    subtitle: "Toca tu nombre y escribe tu PIN.",
    setupBadge: "Configura tu PIN",
    emptyState: "Todavía no hay operadores con PIN. Inicia sesión con tu correo para configurarlo.",
    emailLoginCta: "Iniciar sesión con correo",
    enterPin: "Escribe tu PIN",
    pinFor: (name: string) => `PIN de ${name}`,
    cancel: "Cancelar",
    setupCta: "Crear PIN",
    errors: {
      invalid: "PIN incorrecto.",
      notSet: "Este usuario todavía no tiene PIN configurado.",
      tooManyAttempts: "Demasiados intentos. Toca otro operador o usa tu correo.",
      generic: "No pudimos validar el PIN. Vuelve a intentar.",
      loadFailed: "No pudimos cargar los operadores. Revisa que la app esté corriendo.",
    },
  },
  setupPin: {
    title: "Crea tu PIN de recepción",
    subtitle: "Lo usarás para entrar rápido desde esta computadora.",
    skipCta: "Más tarde",
    submit: "Guardar PIN",
    confirmLabel: "Confirma tu PIN",
    successToast: "PIN configurado. La próxima vez tócalo para entrar.",
    errors: {
      mismatch: "Los dos PINs no coinciden.",
      generic: "No pudimos guardar el PIN. Vuelve a intentar.",
    },
  },
  login: {
    title: "Bienvenido",
    subtitle: "Inicia sesión para entrar a tu Tinta.",
    emailLabel: "Correo electrónico",
    passwordLabel: "Contraseña",
    rememberMe: "Mantenerme conectado",
    submit: "Entrar",
    forgot: "¿Olvidaste tu contraseña?",
    backToPin: "← Volver al PIN",
    errors: {
      invalidCredentials: "Correo o contraseña incorrectos.",
      inactive: "Tu cuenta está desactivada. Contacta al dueño del gym.",
      rateLimit: "Muchos intentos. Espera 1 minuto antes de volver a intentar.",
      offline: "Necesitas internet para iniciar sesión la primera vez.",
      generic: "Algo salió mal. Vuelve a intentar en un momento.",
    },
    trialExpired: {
      title: "Tu prueba terminó",
      body: "Para seguir usando Tinta, activa tu plan.",
      activate: "Activar Tinta Pro",
      later: "Recordármelo después",
    },
  },
  forgot: {
    title: "Recuperar contraseña",
    subtitle: "Te enviaremos un correo con un link para crear una contraseña nueva.",
    emailLabel: "Tu correo electrónico",
    submit: "Enviar instrucciones",
    sent: "Si tu correo está registrado, recibirás un email en unos minutos. Revisa también la carpeta de spam.",
    backToLogin: "Volver al inicio de sesión",
  },
  reset: {
    title: "Crea una contraseña nueva",
    subtitle: "Mínimo 8 caracteres. Que sea fácil de recordar para ti.",
    newPasswordLabel: "Nueva contraseña",
    confirmPasswordLabel: "Repite la contraseña",
    submit: "Guardar contraseña",
    success: "Contraseña actualizada. Inicia sesión con tu nueva contraseña.",
    invalidLink: "Este link ya no es válido. Solicita uno nuevo.",
    expired: "Este link expiró (válido por 1 hora). Solicita uno nuevo.",
    requestNew: "Solicitar nuevo link",
    mismatch: "Las contraseñas no coinciden.",
    short: "Mínimo 8 caracteres.",
  },
  signup: {
    welcome: "Bienvenido a Tinta",
    subtitle: "Vamos a poner tu gym a cuadrar en 5 minutos.",
    fullName: "Tu nombre completo",
    email: "Tu correo electrónico",
    password: "Contraseña",
    confirmPassword: "Repite la contraseña",
    submit: "Crear mi cuenta",
    errors: {
      emailFormat: "Ese correo no se ve bien. Revísalo.",
      emailExists: "Este correo ya tiene una cuenta. ¿Quieres iniciar sesión?",
      passwordShort: "Tu contraseña debe tener al menos 8 caracteres.",
      passwordMismatch: "Las contraseñas no coinciden.",
      offline: "Necesitas internet solo esta vez para crear tu cuenta. Una vez creada, Tinta funciona sin internet.",
    },
  },
};
