export const cashClose = {
  page: {
    title: "Caja",
    dateLabel: "Fecha",
    today: "Hoy",
    yesterday: "Ayer",
    print: "Imprimir corte",
    sendWhatsapp: "Enviar por WhatsApp",
    closeCashRegister: "Hacer corte",
    reopenCashRegister: "Reabrir caja",
    sections: {
      methods: "Por método de pago",
      concepts: "Por concepto",
      operators: "Operadores",
      refunds: "Devoluciones del día",
      expenses: "Gastos pagados desde caja",
      expensesEmpty: "Sin gastos pagados desde la caja ese día.",
      summary: "Efectivo en caja",
    },
    summary: {
      income: "Ingresos brutos",
      refunds: "Devoluciones",
      expenses: "Gastos pagados desde caja",
      net: "Efectivo esperado",
    },
    expenseCategories: {
      renta: "Renta",
      servicios: "Servicios",
      mantenimiento: "Mantenimiento",
      nomina: "Nómina",
      marketing: "Marketing",
      insumos_no_inventariables: "Materiales de uso interno",
      impuestos_y_permisos: "Impuestos y permisos",
      sueldos: "Nómina",
      mercaderia_externa: "Materiales de uso interno",
      otros: "Otros",
    } as Record<string, string>,
    methods: {
      cash: "Efectivo",
      transfer: "Transferencias",
      card: "Tarjeta",
    },
    concepts: {
      membership: "Mensualidades",
      product: "Productos",
      balance_settlement: "Abonos",
      other: "Otros ingresos",
    },
    counts: {
      payments: (n: number) => `${n} ${n === 1 ? "cobro" : "cobros"}`,
      sales: (n: number) => `${n} ${n === 1 ? "venta" : "ventas"}`,
      mix: (payments: number, sales: number) =>
        `${payments} ${payments === 1 ? "cobro" : "cobros"}, ${sales} ${sales === 1 ? "venta" : "ventas"}`,
    },
    total: "Total",
    empty: "No hay movimientos en este día.",
    error: "No pudimos cargar el corte.",
    closedAt: (date: string) => `Caja cerrada el ${date}`,
    outdated: (previous: string, current: string) =>
      `Corte desactualizado: el efectivo esperado cambió de ${previous} a ${current}. Reabre la caja y vuelve a contar.`,
    diffLabel: (amount: string, sign: "+" | "−") =>
      `Diferencia: ${sign}${amount}`,
  },
  modal: {
    title: "Hacer corte",
    calculatedLabel: "Efectivo esperado",
    countedLabel: "¿Cuánto efectivo hay en la caja?",
    diffLabel: "Diferencia",
    reasonLabel: "Si hay diferencia, ¿qué pasó?",
    reasonPlaceholder: "Ej. se entregó cambio de más",
    reasonRequired: "Escribe la razón de la diferencia.",
    skip: "Cancelar",
    submit: "Guardar corte",
    success: "Corte guardado.",
    errors: {
      countedInvalid: "Escribe el efectivo contado.",
      generic: "No pudimos cerrar la caja.",
    },
  },
  reopen: {
    title: "Reabrir caja",
    description:
      "Podrás corregir movimientos y volver a contar. El corte anterior quedará en el historial.",
    onlyIfNotWithdrawn:
      "Reabre sólo si el efectivo del primer corte todavía sigue en el cajón y no fue retirado.",
    cancel: "Conservar corte",
    confirm: "Reabrir caja",
    success: "Caja reabierta.",
    error: "No pudimos reabrir la caja.",
  },
};
