export const checkin = {
  page: {
    title: "Check-in",
    searchPlaceholder: "Buscar socio por nombre o teléfono…",
    searchEmpty: "No encontré a nadie. Revisa el nombre.",
    searching: "Buscando…",
    typeAtLeast: "Escribe al menos 2 letras.",
    operator: (name: string) => `Operador: ${name}`,
    openKiosk: "Modo kiosko",
    goToKiosk: "Ir al kiosko",
    todayCount: (n: number) => `Check-ins hoy: ${n}`,
    recent: "Últimos ingresos",
    recentEmpty: "Aún no hay ingresos hoy.",
    methods: {
      fingerprint: "Huella",
      // ADR-010: el método de respaldo es el número de socio (antes "PIN").
      number: "Número",
      manual: "Buscar",
    },
    overridePrompt: "Presiona O para permitir entrada de todos modos.",
  },
  feedback: {
    idle: "Coloca tu huella en el lector para ingresar.",
    idleNoReader: "Busca al socio o pídele su número de socio.",
    processing: "Identificando…",
    successActive: (days: number) =>
      days === 1 ? "Mensualidad vigente — vence mañana" : `Mensualidad vigente — vence en ${days} días`,
    successExpiringSoon: (days: number) =>
      days === 0
        ? "¡Atención! Vence hoy. Pasa con recepción para renovar."
        : days === 1
        ? "¡Atención! Vence mañana. Pasa con recepción para renovar."
        : `¡Atención! Vence en ${days} días. Pasa con recepción para renovar.`,
    deniedExpired: (days: number) =>
      days === 1
        ? "Membresía vencida hace 1 día. Pasa con recepción."
        : `Membresía vencida hace ${days} días. Pasa con recepción.`,
    deniedInactive: "Socio inactivo. Pasa con recepción.",
    deniedNoMembership: "Sin membresía activa. Pasa con recepción.",
    deniedNotFound: "No encontré a este socio. Vuelve a intentar.",
    overrideBadge: "Permitido por operador",
    expiryPill: (date: string) => `Vence: ${date}`,
  },
  numberPad: {
    title: "Pon tu número de socio para entrar",
    ariaLabel: "Número de socio",
    backspace: "Borrar",
    submit: "Entrar",
    locked: (seconds: number) => `Demasiados intentos. Espera ${seconds} segundos.`,
    invalid: "Número de socio incorrecto. Vuelve a intentar.",
  },
  override: {
    triggerHint: "O — permitir de todos modos",
    title: (name: string) => `¿Permitir entrada a ${name}?`,
    description: "Quedará registrado en el historial.",
    reasonLabel: "Motivo (obligatorio)",
    reasonPlaceholder: "Ej. Vino a pagar después; renovó por WhatsApp; cortesía",
    reasonRequired: "Escribe un motivo (mínimo 5 caracteres).",
    submit: "Permitir entrada",
    cancel: "Cancelar",
    success: (name: string) => `Entrada permitida para ${name}.`,
  },
  kiosk: {
    title: "Tinta — Kiosko",
    waiting: "Coloca tu huella en el lector",
    waitingPin: "Coloca tu huella o pon tu número de socio",
    waitingNoReader: "Pon tu número de socio para entrar",
    waitingNoReaderNoPin: "El kiosko no está configurado todavía. Avísale a recepción.",
    sync: "Sincronizado",
    syncOffline: "Sin conexión — operando offline",
    exitTitle: "Salir del modo kiosko",
    exitDescription: "Para salir, escribe la contraseña del operador.",
    exitPasswordLabel: "Contraseña",
    exitSubmit: "Salir",
    exitCancel: "Cancelar",
    exitWrongPassword: "Contraseña incorrecta.",
    exitNoCache: "Inicia sesión una vez con internet para poder salir desde aquí.",
    exitOffline: "No logro contactar al sistema. Reintenta en unos segundos.",
    exitGenericError: "No pude validar la contraseña. Reintenta.",
    exitButtonAriaLabel: "Salir del modo kiosko",
    exitHint: "Salir: Esc o Ctrl + Shift + K",
  },
  float: {
    title: "Check-in",
    windowTitle: "Tinta · Check-in",
    launcher: "Check-in flotante",
    waiting: "Esperando huella…",
    readerDisconnected: "Lector de huella desconectado.",
    enrollPauseTitle: "Registrando huella…",
    enrollPauseBody: "El check-in se reanuda en un momento.",
    kioskActiveTitle: "El kiosko está activo",
    kioskActiveBody: "Cierra el kiosko para usar el check-in flotante.",
    blockedByKiosk: "El kiosko está activo. Ciérralo para abrir el check-in flotante.",
    kioskBlockedByFloat: "El check-in flotante está activo. Ciérralo para abrir el kiosko.",
    noMatchTitle: "No reconocimos la huella",
    closeAria: "Cerrar check-in flotante",
    lastResultAt: (time: string) => `Hoy ${time}`,
  },
  fingerprint: {
    triggerLabel: "Registrar huella",
    triggerLabelHas: "Volver a registrar huella",
    title: (name: string) => `Registrar huella de ${name}`,
    consentTitle: "Antes de registrar tu huella",
    consentBody: [
      "Tu huella se usa solo para que entres al gym sin tener que dar tu nombre o tu número de socio.",
      "Se guarda encriptada en la computadora del gym.",
      "También se respalda encriptada en la nube de Tinta.",
      "Nadie puede ver la imagen de tu huella — solo un código matemático que sirve para identificarte.",
      "Puedes pedir que la borren cuando quieras.",
    ],
    consentAccept: "Sí, acepto",
    consentCheckbox: "Acepto que se registre mi huella en estos términos.",
    instruction: "Coloca tu dedo en el lector cuando estés listo.",
    capturesLabel: (done: number, total: number) => `Capturas: ${done} de ${total}`,
    processing: "Procesando huella…",
    start: "Empezar",
    cancel: "Cancelar",
    skip: "Saltar por ahora",
    success: "Huella registrada.",
    enrolledBanner: (name: string) =>
      `${name} inscrito. Ahora registra su huella para que entre sin número ni nombre.`,
    autoStartHint: "Empezará automáticamente cuando conectes el lector.",
    errorReader: "No detecto el lector de huella. Conéctalo y vuelve a intentar.",
    errorCapture: "No pude leer bien tu huella. Intenta otra vez.",
    errorGeneric: "No pudimos registrar la huella. Vuelve a intentar.",
    errorCollision: (name: string) => `Esta huella ya está registrada para ${name}.`,
    seeExisting: (name: string) => `Ver perfil de ${name}`,
    collisionCancel: "Cancelar y saltar",
    captureByIndex: [
      "Coloca tu dedo centrado en el lector.",
      "Inclínalo ligeramente hacia la izquierda.",
      "Inclínalo ligeramente hacia la derecha.",
    ] as const,
    waitingPlace: "Esperando dedo en el lector…",
    capturing: (n: number) => `Captura ${n} en proceso…`,
  },
  reader: {
    disconnectedBanner: "Lector de huella desconectado. Usa búsqueda manual o número de socio.",
  },
  audio: {
    success: "/audio/checkin-success.mp3",
    warning: "/audio/checkin-warning.mp3",
    denied: "/audio/checkin-denied.mp3",
  },
};
