export const members = {
  page: {
    title: "Socios",
    new: "Nuevo socio",
    searchPlaceholder: "Buscar por nombre o teléfono…",
    filterStateLabel: "Estado",
    filterPlanLabel: "Plan",
    filterAllPlans: "Todos los planes",
    sortLabel: "Orden",
    sort: {
      nameAsc: "Nombre A–Z",
      nameDesc: "Nombre Z–A",
      expiryAsc: "Vencimiento ↑",
      expiryDesc: "Vencimiento ↓",
      newest: "Más recientes",
      oldest: "Más antiguos",
    },
    states: {
      all: "Todos",
      active: "Activos",
      expiringSoon: "Por vencer",
      expired: "Vencidos",
      inactive: "Inactivos",
    },
    columns: {
      photo: "Foto",
      name: "Nombre",
      plan: "Plan",
      expiry: "Vence",
      lastVisit: "Última visita",
      actions: "Acciones",
    },
    pagination: {
      pageSize: "Mostrar",
      showing: (from: number, to: number, total: number) =>
        `Mostrando ${from}-${to} de ${total}`,
      previous: "Anterior",
      next: "Siguiente",
      noResults: "Sin resultados",
      empty: "Aún no tienes socios. Da de alta el primero.",
    },
    rowActions: {
      pay: "Cobrar",
      checkin: "Check-in",
      more: "Más",
      noPlan: "Sin plan",
    },
    lastVisit: {
      never: "Nunca",
      today: "Hoy",
      yesterday: "Ayer",
      daysAgo: (n: number) => `Hace ${n} días`,
    },
  },
  detail: {
    folio: (folio: string) => `Folio ${folio}`,
    createdAt: (date: string) => `Alta ${date}`,
    membership: {
      title: "Membresía actual",
      none: "Este socio no tiene membresía activa.",
      vigente: "Vigente",
      expiring: (days: number) => `Vence en ${days} ${days === 1 ? "día" : "días"}`,
      expired: (days: number) => `Vencida hace ${Math.abs(days)} ${Math.abs(days) === 1 ? "día" : "días"}`,
      due: "Vence",
      pay: "Cobrar renovación",
      lock: "Ajustar vigencia",
    },
    tabs: {
      payments: "Pagos",
      attendance: "Asistencia",
      notes: "Notas",
      paymentsEmpty: "Aún no hay pagos registrados.",
      attendanceEmpty: "Aún no hay asistencias registradas.",
      notesEmpty: "Sin notas.",
    },
    actions: {
      edit: "Editar",
      markInactive: "Marcar inactivo",
      markActive: "Reactivar",
      assignPin: "Asignar PIN",
    },
    shortcuts: {
      title: "Atajos",
      pay: "P → cobrar",
      checkin: "C → check-in",
      edit: "E → editar",
      close: "Esc → cerrar",
    },
  },
  form: {
    titleNew: "Nuevo socio",
    titleEdit: "Editar socio",
    sections: {
      basics: "Datos básicos",
      membership: "Membresía",
    },
    fields: {
      name: "Nombre completo",
      phone: "Teléfono",
      email: "Email",
      birthdate: "Fecha de nacimiento",
      photo: "Foto",
      notes: "Notas",
      type: "Tipo",
      startDate: "Fecha de inicio",
      paymentMethod: "Método de pago",
    },
    addEmail: "+ Agregar email",
    addBirthdate: "+ Agregar fecha de nacimiento",
    addPhoto: "+ Agregar foto",
    addNotes: "+ Agregar notas",
    chooseFile: "Elegir archivo",
    removePhoto: "Quitar foto",
    expiryPreview: (date: string) => `Vencerá: ${date}`,
    chargeFirstPayment: "Cobrar primer pago ahora",
    chargeAmount: (amount: string) => `Monto: ${amount}`,
    methods: {
      cash: "Efectivo",
      transfer: "Transferencia",
      card: "Tarjeta",
    },
    submitNew: "Guardar socio",
    submitEdit: "Guardar cambios",
    cancel: "Cancelar",
    duplicate: {
      title: "Ya existe un socio con este teléfono",
      bodyPrefix: "Encontramos a ",
      seeExisting: "Ver socio existente",
      createAnyway: "Crear de todos modos",
    },
    success: {
      created: (name: string, expiry: string) => `${name} agregado. Vence ${expiry}.`,
      updated: "Cambios guardados.",
    },
    errors: {
      nameRequired: "Falta el nombre.",
      nameLength: "El nombre debe tener entre 3 y 100 caracteres.",
      phoneRequired: "Necesito 10 dígitos (sin espacios ni guiones).",
      phoneInvalid: "Necesito 10 dígitos (sin espacios ni guiones).",
      emailInvalid: "Email no válido.",
      typeRequired: "Selecciona el tipo de membresía.",
      startDateInvalid: "La fecha de inicio no puede ser tan lejana.",
      photoTooBig: "La foto no debe pasar de 2 MB.",
      photoFormat: "Sube una imagen JPG, PNG o WEBP.",
      methodRequired: "Selecciona el método de pago.",
      generic: "No pudimos guardar. Vuelve a intentar.",
    },
  },
  status: {
    title: "Cambiar estado",
    label: "Estado",
    reasonLabel: "Razón (opcional, queda en historial)",
    reasonPlaceholder: "Ej. Se mudó, se dio de baja, …",
    options: {
      active: "Activo",
      inactive: "Inactivo",
    },
    submit: "Guardar cambio",
    success: "Estado actualizado.",
  },
  lockExpiry: {
    title: "Ajustar vigencia",
    currentExpiry: (date: string) => `Vence actualmente: ${date}`,
    question: "¿Qué quieres hacer?",
    modes: {
      extend: "Extender vigencia",
      set: "Establecer fecha",
      reset: "Quitar ajustes manuales (volver al cálculo automático)",
    },
    daysSuffix: "días → nuevo vencimiento:",
    reasonLabel: "Razón (queda en historial)",
    reasonPlaceholder: "Ej. Cortesía COVID; freeze viaje 30d; compensación cobro doble del 14 abr",
    reasonRequired: "Escribe una razón (mínimo 5 caracteres).",
    daysRequired: "Indica cuántos días.",
    dateRequired: "Selecciona una fecha.",
    submit: "Guardar ajuste",
    cancel: "Cancelar",
    success: (date: string) => `Vigencia actualizada. Nueva fecha: ${date}.`,
    ownerOnly: "Solo el dueño del gym puede ajustar vigencias.",
  },
  pin: {
    title: "PIN del socio",
    description:
      "Cuadra genera un PIN aleatorio de 4 dígitos. Solo se ve esta vez; si se pierde, puedes regenerarlo.",
    generating: "Generando PIN…",
    label: (name: string) => `PIN de ${name}`,
    copy: "Copiar",
    copied: "PIN copiado al portapapeles.",
    done: "Listo",
    regenerate: "Regenerar PIN",
    disclaimer:
      "Compártelo con el socio. Para verlo después, vuelve a esta pantalla y regenera.",
    success: "PIN asignado.",
  },
  types: {
    pageTitle: "Membresías",
    pageSubtitle: "Crea, edita o desactiva los planes que ofreces.",
    addNew: "Agregar membresía",
    columns: {
      name: "Nombre",
      price: "Precio",
      duration: "Duración",
      active: "Activos",
      status: "Estado",
      actions: "Acciones",
    },
    durationDays: (n: number) => `${n} ${n === 1 ? "día" : "días"}`,
    activeMembers: (n: number) => `${n}`,
    statusActive: "Activa",
    statusInactive: "Desactivada",
    edit: "Editar",
    deactivate: "Desactivar",
    deactivateConfirm: {
      title: (name: string) => `¿Desactivar "${name}"?`,
      body: "Tus socios actuales con este plan no se verán afectados, pero ya no podrás dar de alta socios nuevos con él.",
      confirm: "Desactivar",
    },
    form: {
      titleNew: "Nueva membresía",
      titleEdit: "Editar membresía",
      name: "Nombre",
      price: "Precio",
      durationDays: "Duración (días)",
      enrollment: "Cobrar inscripción",
      enrollmentAmount: "Monto de inscripción",
      maintenance: "Cobrar mantenimiento",
      maintenanceAmount: "Monto de mantenimiento",
      maintenanceFreq: "Frecuencia",
      freqMonthly: "Mensual",
      freqAnnual: "Anual",
      submitNew: "Crear membresía",
      submitEdit: "Guardar cambios",
      cancel: "Cancelar",
      changesNotApplied:
        "Los cambios de precio o duración no afectan a socios actuales — solo a renovaciones futuras.",
      errors: {
        nameRequired: "Falta el nombre.",
        nameLength: "El nombre debe tener entre 3 y 100 caracteres.",
        priceRequired: "El precio debe ser mayor a cero.",
        durationRequired: "La duración debe ser al menos 1 día.",
        enrollmentNegative: "La inscripción no puede ser negativa.",
        maintenanceNegative: "El mantenimiento no puede ser negativo.",
        generic: "No pudimos guardar. Vuelve a intentar.",
      },
      success: {
        created: "Membresía creada.",
        updated: "Cambios guardados.",
        deactivated: "Membresía desactivada.",
      },
    },
  },
  errors: {
    loadList: "No pudimos cargar la lista de socios.",
    loadDetail: "No pudimos cargar este socio.",
    loadTypes: "No pudimos cargar las membresías.",
  },
};
