export const products = {
  page: {
    title: "Productos",
    new: "Nuevo producto",
    searchPlaceholder: "Buscar producto…",
    filters: {
      categoryLabel: "Categoría",
      categoryAll: "Todas",
      statusLabel: "Estado",
      statusAll: "Todos",
      statusActive: "Activos",
      statusInactive: "Desactivados",
      lowStockOnly: "Solo existencias bajas",
    },
    columns: {
      photo: "",
      name: "Nombre",
      category: "Categoría",
      price: "Precio",
      stock: "Existencias",
      status: "Estado",
      actions: "Acciones",
    },
    badges: {
      ok: "OK",
      low: "Bajo",
      out: "Agotado",
      active: "Activo",
      inactive: "Desactivado",
    },
    // Card combinada "Existencias bajas" — junta stock bajo + agotados.
    stockHealth: {
      title: "Existencias bajas",
      low: "Bajos",
      out: "Agotados",
      allOk: "todo en orden",
    },
    // Card combinada "Ganancia" — del mes (realizada) + potencial sobre el
    // stock. El margen % va como chip en la fila de potencial.
    margin: {
      cardTitle: "Ganancia",
      monthRow: "Del mes",
      potentialRow: "Potencial",
      coverage: (withCost: number, total: number) =>
        `${withCost} de ${total} con costo`,
    },
    empty: "Aún no hay productos.",
    noResults: "No encontramos productos con esos filtros.",
    rowEdit: "Editar",
    rowAdjust: "Ajustar existencias",
    rowDeactivate: "Desactivar",
    rowReactivate: "Reactivar",
    deactivateConfirm: {
      title: (name: string) => `¿Desactivar "${name}"?`,
      body: "Ya no aparecerá en la pantalla de venta. Puedes reactivarlo después.",
      confirm: "Desactivar",
    },
  },
  form: {
    titleNew: "Nuevo producto",
    titleEdit: "Editar producto",
    fields: {
      name: "Nombre",
      price: "Precio",
      stock: "Existencias",
      category: "Categoría",
      photo: "Foto / Imagen",
      minStock: "Mínimo de existencias",
      initialCost: "Costo unitario",
    },
    photoHint: "Opcional. JPG, PNG o WEBP, máx. 2 MB.",
    minStockHint: "Te avisamos cuando llegue a este nivel.",
    initialCostHint:
      "Se usa para calcular la ganancia. Las existencias iniciales no se registran como compra.",
    margin: {
      heading: "Margen por unidad",
      cost: "Costo promedio",
      price: "Precio",
      marginLabel: "Margen",
      noCost: "Sin costo capturado.",
      captureCost: "Registrar compra",
    },
    customCategory: "Otra (escribir)",
    customCategoryPlaceholder: "Nombre de categoría",
    addAnother: "Agregar otro al guardar este",
    submit: "Guardar",
    cancel: "Cancelar",
    chooseFile: "Subir archivo",
    takePhoto: "Tomar foto",
    removePhoto: "Quitar foto",
    success: {
      created: (name: string) => `${name} agregado.`,
      updated: "Cambios guardados.",
    },
    errors: {
      nameRequired: "Escribe el nombre.",
      nameLength: "El nombre debe tener entre 2 y 100 caracteres.",
      priceInvalid: "El precio debe ser mayor a cero.",
      stockNegative: "Las existencias iniciales no pueden ser negativas.",
      minStockNegative: "El mínimo de existencias no puede ser negativo.",
      categoryRequired: "Selecciona una categoría.",
      photoTooBig: "La foto no debe pasar de 2 MB.",
      photoFormat: "Sube una imagen JPG, PNG o WEBP.",
      generic: "No pudimos guardar. Vuelve a intentar.",
    },
  },
  adjustStock: {
    title: (name: string) => `Ajustar existencias — ${name}`,
    currentStock: (n: number) => `Existencias actuales: ${n}`,
    question: "¿Qué pasó?",
    types: {
      restock: "Llegó mercancía",
      damage: "Se rompió / se perdió",
      count: "Conteo físico",
    },
    typeHints: {
      restock: "Suma a las existencias.",
      damage: "Resta de las existencias.",
      count: "Actualiza las existencias según el conteo.",
    },
    quantityLabel: "Cantidad",
    countLabel: "Conteo real",
    costLabel: "Costo unitario",
    costHint: "Lo que cuesta cada unidad en esta llegada.",
    notesLabel: "Nota (opcional)",
    notesPlaceholder: "Ej. Proveedor Coca, factura #1234",
    submit: "Aplicar ajuste",
    cancel: "Cancelar",
    preview: (next: number) => `Nuevas existencias: ${next}`,
    success: "Existencias actualizadas.",
    errors: {
      quantityInvalid: "La cantidad debe ser mayor a cero.",
      countInvalid: "El conteo no puede ser negativo.",
      damageTooMuch: (avail: number) => `Solo hay ${avail} disponibles.`,
      generic: "No se pudieron ajustar las existencias.",
    },
  },
  errors: {
    loadList: "No pudimos cargar los productos.",
    // Deep-link ?edit=<id> desde el indicador de sync apuntó a un producto
    // que ya no se encontró (borrado o fuera del catálogo).
    deepLinkNotFound: "No encontramos ese producto. Búscalo en la lista.",
  },
};
