export const products = {
  page: {
    title: "Productos",
    new: "Nuevo producto",
    searchPlaceholder: "Buscar producto…",
    filters: {
      categoryLabel: "Categoría",
      categoryAll: "Todas",
      statusLabel: "Estado",
      statusAll: "Todos",
      statusActive: "Activos",
      statusInactive: "Desactivados",
      lowStockOnly: "Solo stock bajo",
    },
    columns: {
      photo: "",
      name: "Nombre",
      category: "Categoría",
      price: "Precio",
      stock: "Stock",
      status: "Estado",
      actions: "Acciones",
    },
    badges: {
      ok: "OK",
      low: "Bajo",
      out: "Agotado",
      active: "Activo",
      inactive: "Desactivado",
    },
    empty: "Aún no tienes productos. Crea el primero.",
    noResults: "No encontramos productos con esos filtros.",
    rowEdit: "Editar",
    rowAdjust: "Ajustar stock",
    rowDeactivate: "Desactivar",
    rowReactivate: "Reactivar",
    deactivateConfirm: {
      title: (name: string) => `¿Desactivar "${name}"?`,
      body: "Ya no aparecerá en la pantalla de venta. Puedes reactivarlo después.",
      confirm: "Desactivar",
    },
  },
  form: {
    titleNew: "Nuevo producto",
    titleEdit: "Editar producto",
    fields: {
      name: "Nombre",
      price: "Precio",
      stock: "Stock inicial",
      category: "Categoría",
      photo: "Foto / Imagen",
      minStock: "Stock mínimo",
    },
    photoHint: "Opcional. JPG, PNG o WEBP, máx. 2 MB.",
    minStockHint: "Te avisamos cuando llegue a este nivel.",
    customCategory: "Otra (escribir)",
    customCategoryPlaceholder: "Nombre de categoría",
    addAnother: "Agregar otro al guardar este",
    submit: "Guardar",
    cancel: "Cancelar",
    chooseFile: "Elegir archivo",
    removePhoto: "Quitar foto",
    success: {
      created: (name: string) => `${name} agregado.`,
      updated: "Cambios guardados.",
    },
    errors: {
      nameRequired: "Falta el nombre.",
      nameLength: "El nombre debe tener entre 2 y 100 caracteres.",
      priceInvalid: "El precio debe ser mayor a cero.",
      stockNegative: "El stock no puede ser negativo.",
      minStockNegative: "El stock mínimo no puede ser negativo.",
      categoryRequired: "Selecciona una categoría.",
      photoTooBig: "La foto no debe pasar de 2 MB.",
      photoFormat: "Sube una imagen JPG, PNG o WEBP.",
      generic: "No pudimos guardar. Vuelve a intentar.",
    },
  },
  adjustStock: {
    title: (name: string) => `Ajustar stock — ${name}`,
    currentStock: (n: number) => `Stock actual: ${n}`,
    question: "¿Qué pasó?",
    types: {
      restock: "Llegó mercancía",
      damage: "Se rompió / se perdió",
      count: "Conteo físico",
    },
    typeHints: {
      restock: "Suma al stock actual.",
      damage: "Resta del stock actual.",
      count: "Reemplaza el stock por el valor real.",
    },
    quantityLabel: "Cantidad",
    countLabel: "Stock real",
    costLabel: "Costo total (opcional)",
    notesLabel: "Nota (opcional)",
    notesPlaceholder: "Ej. Proveedor Coca, factura #1234",
    submit: "Aplicar ajuste",
    cancel: "Cancelar",
    preview: (next: number) => `Stock nuevo: ${next}`,
    success: "Stock actualizado.",
    errors: {
      quantityInvalid: "La cantidad debe ser mayor a cero.",
      countInvalid: "El stock real no puede ser negativo.",
      damageTooMuch: (avail: number) => `Solo hay ${avail} disponibles.`,
      generic: "No pudimos ajustar el stock.",
    },
  },
  errors: {
    loadList: "No pudimos cargar los productos.",
  },
};
