export const reports = {
  page: {
    title: "Reportes",
    subtitle: "Ingresos, gastos y caja por período.",
    periodLabel: "Período",
    customFromLabel: "Desde",
    customToLabel: "Hasta",
    customInvalid: "Selecciona desde y hasta para ver el reporte.",
    error: "No pudimos cargar el reporte.",
    empty: "Sin movimientos en este período.",
    exportPdf: "Descargar PDF",
    exportXlsx: "Descargar XLSX",
    exportingPdf: "Preparando PDF…",
    exportingXlsx: "Preparando XLSX…",
    exportSuccess: "Descarga lista.",
    exportError: "No pudimos preparar el archivo.",
  },
  periods: {
    today: "Hoy",
    week: "Últimos 7 días",
    month: "Este mes",
    last_month: "Mes pasado",
    "3_months": "Últimos 3 meses",
    year: "Últimos 12 meses",
    custom: "Personalizado",
  },
  kpis: {
    operatingResult: "Resultado del período",
    operatingResultHint: "Ingresos − salidas registradas",
    cashFlow: "Movimiento neto de caja",
    cashFlowHint: "Sólo movimientos físicos de la caja de recepción",
    cashCounted: "Último conteo de efectivo",
    cashDifference: "Diferencia de caja",
    income: "Ingresos",
    membershipIncome: "Cobros de membresías",
    productSales: "Cobros de productos",
    otherIncome: "Otros ingresos",
    newMembers: "Socios nuevos",
    checkins: "Asistencias",
    refunds: "Devoluciones",
    inventoryPurchases: "Compras pagadas para reventa",
    cogs: "Costo de productos vendidos",
    expensesGeneral: "Gastos de operación",
    criticalStock: "Existencias bajas",
    criticalStockHint: (out: number, low: number) =>
      out > 0
        ? `${out} sin existencias · ${low} bajo mínimo`
        : low > 0
        ? `${low} bajo mínimo`
        : "Todo en orden",
  },
  charts: {
    incomeByDay: "Ingresos por día",
    incomeVsExpensesByDay: "Ingresos vs salidas registradas por día",
    incomeVsExpensesHint: "Línea azul: ingresos · línea roja: salidas registradas",
    checkinsByDay: "Asistencias por día",
    legendIncome: "Ingresos",
    legendExpenses: "Salidas registradas",
  },
  byMethod: {
    title: "Por método de pago",
    cash: "Efectivo",
    transfer: "Transferencias",
    card: "Tarjeta",
  },
  byCategory: {
    title: "Gastos por categoría",
    description: "Desglose de los gastos de operación del período.",
    empty: "Sin gastos clasificados en este período.",
  },
  topMembers: {
    title: "Socios que más pagaron",
    empty: "Sin pagos en este período.",
    columns: {
      member: "Socio",
      payments: "# Pagos",
      total: "Total",
    },
    paymentsCount: (n: number) => (n === 1 ? "1 pago" : `${n} pagos`),
  },
  topProducts: {
    title: "Productos más vendidos",
    description: "Ranking por ventas cobradas del período.",
    empty: "Sin ventas de productos en este período.",
    columns: {
      product: "Producto",
      quantity: "Unidades",
      revenue: "Ventas cobradas",
    },
    quantityValue: (n: number) =>
      n === 1 ? "1 unidad" : `${n.toLocaleString("es-MX")} unidades`,
  },
  recentPayments: {
    title: "Cobros del período",
    empty: "Sin cobros.",
    columns: {
      date: "Fecha",
      member: "Socio",
      concept: "Concepto",
      method: "Método",
      amount: "Monto",
    },
  },
  inventoryCosts: {
    title: "Compras de productos",
    description: "Dinero usado para surtir productos en el período.",
    empty: "Sin compras registradas en este período.",
    hint: "Captura el costo al surtir productos para que aparezca aquí.",
    totalLabel: "Total:",
    columns: {
      date: "Fecha",
      product: "Producto",
      qty: "Unidades",
      costUnit: "Costo unit.",
      costTotal: "Total",
      reason: "Nota",
    },
  },
  expensesSection: {
    title: "Gastos del período",
    description: "Renta, servicios, sueldos y otros gastos de operación.",
    empty: "Sin gastos registrados en este período.",
    hint: "Ve a Gastos para capturar uno.",
    totalLabel: "Total:",
    columns: {
      date: "Fecha",
      category: "Categoría",
      description: "Descripción",
      method: "Método",
      amount: "Monto",
    },
  },
  expenseCategories: {
    renta: "Renta",
    servicios: "Servicios",
    nomina: "Nómina",
    mantenimiento: "Mantenimiento",
    marketing: "Publicidad y promoción",
    insumos_no_inventariables: "Materiales de uso interno",
    impuestos_y_permisos: "Impuestos y permisos",
    // Aliases de lectura para instalaciones todavía sin migrar.
    sueldos: "Nómina",
    mercaderia_externa: "Materiales de uso interno",
    otros: "Otros",
  } as Record<string, string>,
  expenseMethods: {
    cash: "Efectivo",
    transfer: "Transferencia",
    card: "Tarjeta",
  } as Record<string, string>,
  drillDown: {
    incomeTitle: (day: string) => `Cobros del ${day}`,
    incomeEmpty: "Sin cobros ese día.",
    checkinsTitle: (day: string) => `Asistencias del ${day}`,
    checkinsEmpty: "Sin asistencias ese día.",
    close: "Cerrar",
    loading: "Cargando…",
  },
};
