export const sales = {
  page: {
    title: "Venta rápida",
    associate: "Asociar a socio",
    associated: (name: string) => `Socio: ${name}`,
    removeAssociation: "Quitar",
    associateSearchPlaceholder: "Buscar por nombre o teléfono…",
    associateNoResults: "Sin resultados",
    empty: "Aún no hay productos para vender.",
    emptyHint: "Agrega productos en la sección de Productos.",
    uncategorized: "Sin categoría",
    cart: {
      title: "Carrito",
      clear: "Limpiar",
      empty: "Empieza haciendo clic en un producto.",
      total: "Total",
      methods: {
        cash: "Efectivo",
        transfer: "Transferencia",
        card: "Tarjeta",
      },
      submit: (amount: string) => `Cobrar ${amount}`,
      remove: "Quitar",
      qtyLabel: "Cantidad",
    },
    change: {
      label: "Te dieron",
      result: (amount: string) => `Cambio: ${amount}`,
      shortfall: (amount: string) => `Falta: ${amount}`,
      exact: "Exacto",
      placeholder: "0",
    },
    debt: {
      chip: (amount: string) => `Debe ${amount} · Cobrar deuda`,
    },
    checkout: {
      title: "Cobrar",
      totalLabel: "Total a cobrar",
      itemsSummary: (n: number) => (n === 1 ? "1 producto" : `${n} productos`),
      fiado: "Fiado",
      fiadoNeedsMember: "Asocia al socio (arriba) para poder fiar.",
      fiadoQuestion: "¿Cuánto te deja ahora?",
      fiadoMethodQuestion: "¿Cómo te paga lo de ahora?",
      cashQuestion: "¿Con cuánto te pagan?",
      cardHint: "Cobra en la terminal y confirma aquí.",
      transferHint: "Verifica que llegó la transferencia y confirma aquí.",
      confirm: (amount: string) => `Confirmar — cobrar ${amount}`,
      confirmFiado: (paid: string, debt: string) =>
        `Confirmar — cobrar ${paid} · quedan ${debt}`,
    },
    credit: {
      requiresMember: "Asocia un socio para poder fiar.",
      balanceLabel: (amount: string) => `Queda a deber: ${amount}`,
      paidExceedsTotal: "El monto cobrado no puede ser mayor al total.",
      paidMustBePositive: "Debes cobrar al menos algo ahora.",
    },
    badges: {
      out: "0✕",
      low: (n: number) => `${n}⚠`,
      stock: (n: number) => String(n),
    },
    tooltips: {
      out: "Sin stock",
      low: "Stock bajo",
      rightClick: "Click derecho o mantén presionado para cantidad personalizada",
    },
    searchPlaceholder: "Buscar producto…",
    noSearchResults: "Sin productos que coincidan.",
    showOutOfStock: "Ver agotados",
    restock: {
      title: (name: string) => `Registrar mercancía — ${name}`,
      description:
        "El sistema dice que no quedan. Si te llegaron unidades sin registrar, anótalas aquí y se agregan al carrito.",
      qtyLabel: "¿Cuántas te llegaron?",
      costLabel: "Costo unitario (opcional)",
      costHint: "Cuánto pagaste por cada una. Queda en el historial de egresos.",
      reasonDefault: "Recibido en venta",
      submit: "Registrar y agregar",
      cancel: "Cancelar",
      success: (qty: number, name: string) =>
        qty === 1 ? `${name} agregado al stock y al carrito.` : `${qty} ${name} agregados al stock y al carrito.`,
      errors: {
        qtyInvalid: "La cantidad debe ser mayor a cero.",
        generic: "No pudimos registrar la mercancía.",
      },
    },
    outOfStockTap: "Sin stock — toca para registrar",
    quantityModal: {
      title: (name: string) => `Cantidad — ${name}`,
      label: "¿Cuántos vas a vender?",
      stockLabel: (n: number) => `Stock disponible: ${n}`,
      tooMuch: (avail: number) => `Solo hay ${avail} disponibles.`,
      submit: "Agregar",
      cancel: "Cancelar",
    },
    success: {
      online: (amount: string) => `${amount} cobrados.`,
      offline: "Guardado. Se sincronizará cuando vuelva la conexión.",
    },
    errors: {
      cartEmpty: "Agrega al menos un producto al carrito.",
      stockInsufficient: (name: string, avail: number) =>
        `Solo hay ${avail} de ${name}. Ajusta cantidad.`,
      generic: "No pudimos registrar la venta.",
    },
  },
};
