export const shell = {
  nav: {
    dashboard: "Inicio",
    attention: "Atención",
    members: "Socios",
    billing: "Cobros",
    sales: "Venta rápida",
    products: "Productos",
    expenses: "Gastos",
    membershipTypes: "Membresías y promociones",
    checkin: "Check-in",
    challenges: "Retos",
    reports: "Reportes",
    settings: "Ajustes",
  },
  navGroups: {
    operation: "Operación",
    catalog: "Catálogo",
    programs: "Programas",
    reports: "Reportes",
    settings: "Ajustes",
  },
  user: {
    logout: "Cerrar sesión",
    profile: "Mi perfil",
  },
  theme: {
    toggle: "Cambiar tema",
    light: "Modo claro",
    dark: "Modo noche",
    system: "Seguir al sistema",
  },
  sync: {
    online: "Sincronizado",
    syncing: "Sincronizando…",
    offline: "Sin internet, todo guardado en esta laptop.",
    error: "Hay un problema sincronizando.",
    authInvalid: "Vuelve a iniciar sesión para sincronizar.",
    authInvalidHint:
      "La credencial de esta laptop expiró. Tus cambios siguen guardados; vuelve a iniciar sesión para reanudar el sync.",
    detailsTitle: "Estado de sincronización",
    lastSync: "Último sync exitoso",
    pending: "Cambios pendientes",
    lastError: "Último error",
    never: "Nunca",
    none: "Ninguno",
    triggerNow: "Sincronizar ahora",
    relogin: "Iniciar sesión",
  },
};
