export const shell = {
  nav: {
    dashboard: "Dashboard",
    attention: "Atención",
    members: "Socios",
    billing: "Cobros",
    sales: "Venta rápida",
    products: "Productos",
    checkin: "Check-in",
    reports: "Reportes",
    settings: "Configuración",
  },
  user: {
    logout: "Cerrar sesión",
    profile: "Mi perfil",
  },
  theme: {
    toggle: "Cambiar tema",
    light: "Modo claro",
    dark: "Modo noche",
    system: "Seguir al sistema",
  },
  sync: {
    online: "Sincronizado",
    syncing: "Sincronizando…",
    offline: "Sin internet, todo guardado en esta laptop.",
    error: "Hay un problema sincronizando.",
    detailsTitle: "Estado de sincronización",
    lastSync: "Último sync exitoso",
    pending: "Cambios pendientes",
    lastError: "Último error",
    never: "Nunca",
    none: "Ninguno",
    triggerNow: "Sincronizar ahora",
  },
};
