export const wizard = {
  progress: (current: number, total: number) => `Paso ${current} de ${total}`,
  back: "Atrás",
  continue: "Continuar",
  step2: {
    title: "Cuéntanos de tu gym",
    nameLabel: "¿Cómo se llama tu gym?",
    namePlaceholder: "ej: Gym Bros",
    cityLabel: "¿En qué ciudad están?",
    cityPlaceholder: "Querétaro, Qro.",
    whatsappLabel: "WhatsApp del gym",
    whatsappHint: "Es el número que verán tus socios.",
  },
  step3: {
    title: "Vamos a agregar las membresías que vendes",
    subtitle: "Empieza con la principal.",
    nameLabel: "Nombre del plan",
    namePlaceholder: "ej: Mensual",
    priceLabel: "Precio",
    durationLabel: "¿Cuánto dura?",
    durationOptions: [
      { value: "1d", label: "1 día", days: 1 },
      { value: "1w", label: "1 semana", days: 7 },
      { value: "1m", label: "1 mes", days: 30 },
      { value: "3m", label: "3 meses", days: 90 },
      { value: "1y", label: "1 año", days: 365 },
      { value: "custom", label: "Otra…", days: 0 },
    ],
    customCount: "Cantidad",
    customUnit: "Unidad",
    enrollmentToggle: "¿Cobras inscripción?",
    enrollmentLabel: "Monto de inscripción",
    maintenanceToggle: "¿Cobras mantenimiento?",
    maintenanceLabel: "Monto de mantenimiento",
    maintenanceFreq: "Cada cuántos meses",
    saveAndAddAnother: "Guardar y agregar otra",
    saveAndContinue: "Guardar y continuar",
    suggestionsTitle: "¿No sabes qué poner?",
    suggestionsBody: "Estos son los planes más comunes en gyms como el tuyo:",
    useSuggestions: "Usar estos como base",
  },
  step4: {
    title: "¿Cómo te pagan tus socios?",
    subtitle: "Marca todos los que aceptas.",
    cash: "Efectivo",
    transfer: "Transferencia",
    card: "Tarjeta",
  },
  step5: {
    title: "¡Tu gym ya está en Cuadra!",
    summaryTitle: "Acabas de crear:",
    cta: "Empezar a usar Cuadra",
  },
  errors: {
    fieldRequired: (field: string) => `Falta el ${field}. Es obligatorio.`,
    pricePositive: "El precio debe ser mayor a cero.",
    durationPositive: "La duración debe ser al menos 1 día.",
    whatsappFormat: "Necesitamos 10 dígitos. Ejemplo: 442 123 4567.",
    nameLength: "Máximo 100 caracteres.",
  },
  defaultSuggestions: [
    { name: "Mensual", price: 500, duration_days: 30 },
    { name: "Trimestral", price: 1300, duration_days: 90 },
    { name: "Visita", price: 50, duration_days: 1 },
  ],
};
